 INSERT INTO configure (language, name, status) VALUES ('AB','ABKHAZ', 'A');
 INSERT INTO configure (language, name, status) VALUES ('AA','AFAR', 'A');
 INSERT INTO configure (language, name, status) VALUES ('AF','AFRIKAANS', 'A');
 INSERT INTO configure (language, name, status) VALUES ('AK','AKAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SQ','ALBANIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('AM','AMHARIC', 'A');
 INSERT INTO configure (language, name, status) VALUES ('AR','ARABIC', 'A');
 INSERT INTO configure (language, name, status) VALUES ('AN','ARAGONESE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('HY','ARMENIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('AS','ASSAMESE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('AV','AVARIC', 'A');
 INSERT INTO configure (language, name, status) VALUES ('AE','AVESTAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('AY','AYMARA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('AZ','AZERBAIJANI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('BM','BAMBARA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('BA','BASHKIR', 'A');
 INSERT INTO configure (language, name, status) VALUES ('EU','BASQUE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('BE','BELARUSIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('BN','BENGALI, BANGLA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('BH','BIHARI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('BI','BISLAMA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('BS','BOSNIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('BR','BRETON', 'A');
 INSERT INTO configure (language, name, status) VALUES ('BG','BULGARIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('MY','BURMESE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('CA','CATALAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('CH','CHAMORRO', 'A');
 INSERT INTO configure (language, name, status) VALUES ('CE','CHECHEN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('NY','CHICHEWA, CHEWA, NYANJA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('ZH','CHINESE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('CV','CHUVASH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KW','CORNISH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('CO','CORSICAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('CR','CREE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('HR','CROATIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('CS','CZECH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('DA','DANISH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('DV','DIVEHI, DHIVEHI, MALDIVIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('NL','DUTCH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('DZ','DZONGKHA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('EN','ENGLISH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('EO','ESPERANTO', 'A');
 INSERT INTO configure (language, name, status) VALUES ('ET','ESTONIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('EE','EWE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('FO','FAROESE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('FJ','FIJIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('FI','FINNISH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('FR','FRENCH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('FF','FULA, FULAH, PULAAR, PULAR', 'A');
 INSERT INTO configure (language, name, status) VALUES ('GL','GALICIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KA','GEORGIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('DE','GERMAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('EL','GREEK (MODERN)', 'A');
 INSERT INTO configure (language, name, status) VALUES ('GN','GUARANÍ', 'A');
 INSERT INTO configure (language, name, status) VALUES ('GU','GUJARATI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('HT','HAITIAN, HAITIAN CREOLE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('HA','HAUSA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('HE','HEBREW (MODERN)', 'A');
 INSERT INTO configure (language, name, status) VALUES ('HZ','HERERO', 'A');
 INSERT INTO configure (language, name, status) VALUES ('HI','HINDI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('HO','HIRI MOTU', 'A');
 INSERT INTO configure (language, name, status) VALUES ('HU','HUNGARIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('IA','INTERLINGUA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('ID','INDONESIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('IE','INTERLINGUE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('GA','IRISH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('IG','IGBO', 'A');
 INSERT INTO configure (language, name, status) VALUES ('IK','INUPIAQ', 'A');
 INSERT INTO configure (language, name, status) VALUES ('IO','IDO', 'A');
 INSERT INTO configure (language, name, status) VALUES ('IS','ICELANDIC', 'A');
 INSERT INTO configure (language, name, status) VALUES ('IT','ITALIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('IU','INUKTITUT', 'A');
 INSERT INTO configure (language, name, status) VALUES ('JA','JAPANESE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('JV','JAVANESE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KL','KALAALLISUT, GREENLANDIC', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KN','KANNADA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KR','KANURI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KS','KASHMIRI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KK','KAZAKH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KM','KHMER', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KI','KIKUYU, GIKUYU', 'A');
 INSERT INTO configure (language, name, status) VALUES ('RW','KINYARWANDA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KY','KYRGYZ', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KV','KOMI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KG','KONGO', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KO','KOREAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KU','KURDISH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('KJ','KWANYAMA, KUANYAMA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('LA','LATIN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('LB','LUXEMBOURGISH, LETZEBURGESCH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('LG','GANDA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('LI','LIMBURGISH, LIMBURGAN, LIMBURGER', 'A');
 INSERT INTO configure (language, name, status) VALUES ('LN','LINGALA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('LO','LAO', 'A');
 INSERT INTO configure (language, name, status) VALUES ('LT','LITHUANIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('LU','LUBA-KATANGA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('LV','LATVIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('GV','MANX', 'A');
 INSERT INTO configure (language, name, status) VALUES ('MK','MACEDONIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('MG','MALAGASY', 'A');
 INSERT INTO configure (language, name, status) VALUES ('MS','MALAY', 'A');
 INSERT INTO configure (language, name, status) VALUES ('ML','MALAYALAM', 'A');
 INSERT INTO configure (language, name, status) VALUES ('MT','MALTESE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('MI','MĀORI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('MR','MARATHI (MARĀṬHĪ)', 'A');
 INSERT INTO configure (language, name, status) VALUES ('MH','MARSHALLESE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('MN','MONGOLIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('NA','NAURUAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('NV','NAVAJO, NAVAHO', 'A');
 INSERT INTO configure (language, name, status) VALUES ('ND','NORTHERN NDEBELE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('NE','NEPALI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('NG','NDONGA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('NB','NORWEGIAN BOKMÅL', 'A');
 INSERT INTO configure (language, name, status) VALUES ('NN','NORWEGIAN NYNORSK', 'A');
 INSERT INTO configure (language, name, status) VALUES ('NO','NORWEGIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('II','NUOSU', 'A');
 INSERT INTO configure (language, name, status) VALUES ('NR','SOUTHERN NDEBELE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('OC','OCCITAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('OJ','OJIBWE, OJIBWA', 'A');
-- INSERT INTO configure (language, name, status) VALUES ('CU','OLD CHURCH SLAVONIC, CHURCH SLAVONIC, OLD BULGARIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('OM','OROMO', 'A');
 INSERT INTO configure (language, name, status) VALUES ('OR','ORIYA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('OS','OSSETIAN, OSSETIC', 'A');
 INSERT INTO configure (language, name, status) VALUES ('PA','PANJABI, PUNJABI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('PI','PĀLI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('FA','PERSIAN (FARSI)', 'A');
 INSERT INTO configure (language, name, status) VALUES ('PL','POLISH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('PS','PASHTO, PUSHTO', 'A');
 INSERT INTO configure (language, name, status) VALUES ('PT','PORTUGUESE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('QU','QUECHUA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('RM','ROMANSH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('RN','KIRUNDI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('RC','REUNIONESE, REUNION CREOLE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('RO','ROMANIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('RU','RUSSIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SA','SANSKRIT (SAṀSKṚTA)', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SC','SARDINIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SD','SINDHI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SE','NORTHERN SAMI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SM','SAMOAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SG','SANGO', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SR','SERBIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('GD','SCOTTISH GAELIC, GAELIC', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SN','SHONA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SI','SINHALESE, SINHALA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SK','SLOVAK', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SL','SLOVENE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SO','SOMALI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('ST','SOUTHERN SOTHO', 'A');
 INSERT INTO configure (language, name, status) VALUES ('ES','SPANISH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SU','SUNDANESE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SW','SWAHILI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SS','SWATI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('SV','SWEDISH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TA','TAMIL', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TE','TELUGU', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TG','TAJIK', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TH','THAI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TI','TIGRINYA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('BO','TIBETAN STANDARD, TIBETAN, CENTRAL', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TK','TURKMEN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TL','TAGALOG', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TN','TSWANA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TO','TONGA (TONGA ISLANDS)', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TR','TURKISH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TS','TSONGA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TT','TATAR', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TW','TWI', 'A');
 INSERT INTO configure (language, name, status) VALUES ('TY','TAHITIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('UG','UYGHUR', 'A');
 INSERT INTO configure (language, name, status) VALUES ('UK','UKRAINIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('UR','URDU', 'A');
 INSERT INTO configure (language, name, status) VALUES ('UZ','UZBEK', 'A');
 INSERT INTO configure (language, name, status) VALUES ('VE','VENDA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('VI','VIETNAMESE', 'A');
 INSERT INTO configure (language, name, status) VALUES ('VO','VOLAPÜK', 'A');
 INSERT INTO configure (language, name, status) VALUES ('WA','WALLOON', 'A');
 INSERT INTO configure (language, name, status) VALUES ('CY','WELSH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('WO','WOLOF', 'A');
 INSERT INTO configure (language, name, status) VALUES ('FY','WESTERN FRISIAN', 'A');
 INSERT INTO configure (language, name, status) VALUES ('XH','XHOSA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('YI','YIDDISH', 'A');
 INSERT INTO configure (language, name, status) VALUES ('YO','YORUBA', 'A');
 INSERT INTO configure (language, name, status) VALUES ('ZA','ZHUANG, CHUANG', 'A');
 INSERT INTO configure (language, name, status) VALUES ('ZU','ZULU', 'A');
